export type InstructorMonthlyRecord = {
  instructorId: string;
  instructorName: string;
  branch: string;
  status: "active" | "on_leave";
  month: string;
  sessions: number;
  attendanceRate: number;
  evaluationCompletionRate: number;
  averageEvaluation: number;
};

export const ACADEMY_BRANCHES = ["مدينة نصر", "المعادي", "الشيخ زايد"] as const;

export const PERFORMANCE_MONTHS = [
  { value: "2026-09", label: "سبتمبر ٢٠٢٦" },
  { value: "2026-08", label: "أغسطس ٢٠٢٦" },
  { value: "2026-07", label: "يوليو ٢٠٢٦" },
] as const;

// Local illustrative data only; not connected to attendance or evaluation records.
export const INSTRUCTOR_MONTHLY_PERFORMANCE: InstructorMonthlyRecord[] = [
  {
    instructorId: "USR-0202",
    instructorName: "عمر سامح",
    branch: "مدينة نصر",
    status: "active",
    month: "2026-09",
    sessions: 18,
    attendanceRate: 88,
    evaluationCompletionRate: 83,
    averageEvaluation: 4.2,
  },
  {
    instructorId: "USR-0202",
    instructorName: "عمر سامح",
    branch: "مدينة نصر",
    status: "active",
    month: "2026-08",
    sessions: 16,
    attendanceRate: 84,
    evaluationCompletionRate: 78,
    averageEvaluation: 4.0,
  },
  {
    instructorId: "USR-0202",
    instructorName: "عمر سامح",
    branch: "مدينة نصر",
    status: "active",
    month: "2026-07",
    sessions: 17,
    attendanceRate: 86,
    evaluationCompletionRate: 80,
    averageEvaluation: 4.1,
  },
  {
    instructorId: "USR-0208",
    instructorName: "دينا مصطفى",
    branch: "مدينة نصر",
    status: "active",
    month: "2026-09",
    sessions: 17,
    attendanceRate: 92,
    evaluationCompletionRate: 86,
    averageEvaluation: 4.4,
  },
  {
    instructorId: "USR-0208",
    instructorName: "دينا مصطفى",
    branch: "مدينة نصر",
    status: "active",
    month: "2026-08",
    sessions: 15,
    attendanceRate: 90,
    evaluationCompletionRate: 82,
    averageEvaluation: 4.3,
  },
  {
    instructorId: "USR-0208",
    instructorName: "دينا مصطفى",
    branch: "مدينة نصر",
    status: "active",
    month: "2026-07",
    sessions: 16,
    attendanceRate: 89,
    evaluationCompletionRate: 84,
    averageEvaluation: 4.2,
  },
  {
    instructorId: "USR-0209",
    instructorName: "كريم أشرف",
    branch: "مدينة نصر",
    status: "active",
    month: "2026-09",
    sessions: 16,
    attendanceRate: 85,
    evaluationCompletionRate: 79,
    averageEvaluation: 4.0,
  },
  {
    instructorId: "USR-0209",
    instructorName: "كريم أشرف",
    branch: "مدينة نصر",
    status: "active",
    month: "2026-08",
    sessions: 14,
    attendanceRate: 82,
    evaluationCompletionRate: 76,
    averageEvaluation: 3.9,
  },
  {
    instructorId: "USR-0209",
    instructorName: "كريم أشرف",
    branch: "مدينة نصر",
    status: "active",
    month: "2026-07",
    sessions: 15,
    attendanceRate: 87,
    evaluationCompletionRate: 81,
    averageEvaluation: 4.1,
  },
  {
    instructorId: "USR-0203",
    instructorName: "سارة خالد",
    branch: "المعادي",
    status: "active",
    month: "2026-09",
    sessions: 19,
    attendanceRate: 90,
    evaluationCompletionRate: 89,
    averageEvaluation: 4.5,
  },
  {
    instructorId: "USR-0203",
    instructorName: "سارة خالد",
    branch: "المعادي",
    status: "active",
    month: "2026-08",
    sessions: 17,
    attendanceRate: 87,
    evaluationCompletionRate: 84,
    averageEvaluation: 4.3,
  },
  {
    instructorId: "USR-0203",
    instructorName: "سارة خالد",
    branch: "المعادي",
    status: "active",
    month: "2026-07",
    sessions: 18,
    attendanceRate: 88,
    evaluationCompletionRate: 85,
    averageEvaluation: 4.4,
  },
  {
    instructorId: "USR-0204",
    instructorName: "يوسف عماد",
    branch: "الشيخ زايد",
    status: "on_leave",
    month: "2026-09",
    sessions: 11,
    attendanceRate: 81,
    evaluationCompletionRate: 75,
    averageEvaluation: 3.8,
  },
  {
    instructorId: "USR-0204",
    instructorName: "يوسف عماد",
    branch: "الشيخ زايد",
    status: "on_leave",
    month: "2026-08",
    sessions: 14,
    attendanceRate: 85,
    evaluationCompletionRate: 79,
    averageEvaluation: 4.0,
  },
  {
    instructorId: "USR-0204",
    instructorName: "يوسف عماد",
    branch: "الشيخ زايد",
    status: "on_leave",
    month: "2026-07",
    sessions: 15,
    attendanceRate: 86,
    evaluationCompletionRate: 81,
    averageEvaluation: 4.1,
  },
];
