import { useMemo, useState, type FormEvent, type ReactNode } from "react";
import { AlertCircle, ArrowDownToLine, ArrowUpLeft, BarChart3, CalendarDays, Check, CheckCircle2, ChevronLeft, CircleHelp, Clock3, CreditCard, FileCheck2, FileText, LayoutDashboard, LogOut, MapPin, Menu, Plus, Search, Settings, ShieldCheck, TrendingDown, TrendingUp, Wallet, X } from "lucide-react";
import { toast } from "sonner";
import { useLocation } from "wouter";
import RoleDashboardShell from "@/components/RoleDashboardShell";
import PageHeader from "@/components/PageHeader";
import RoleScopeCard from "@/components/RoleScopeCard";

type View = "overview" | "collections" | "expenses" | "reports";
type InvoiceStatus = "partial" | "overdue" | "paid" | "unpaid";
type ExpenseStatus = "pending" | "approved" | "rejected";
type Invoice = { id: string; number: string; student: string; parent: string; branch: string; course: string; total: number; collected: number; due: string };
type Expense = { id: string; description: string; branch: string; category: string; amount: number; date: string; status: ExpenseStatus; createdBy: string; reason?: string };
const INVOICES: Invoice[] = [
  { id: "INV-0908", number: "MAD-NSR-2026-0908", student: "ياسين محمد علي", parent: "محمد علي", branch: "مدينة نصر", course: "روبوتكس مستوى 2", total: 4800, collected: 2400, due: "26 سبتمبر" },
  { id: "INV-0904", number: "MAD-NSR-2026-0904", student: "عمر خالد إبراهيم", parent: "نهى إبراهيم", branch: "مدينة نصر", course: "دوائر إلكترونية", total: 4500, collected: 1500, due: "20 سبتمبر" },
  { id: "INV-0905", number: "MAD-MAD-2026-0905", student: "ليلى أحمد محمود", parent: "أحمد محمود", branch: "المعادي", course: "برمجة للمبتدئين", total: 5200, collected: 5200, due: "18 سبتمبر" },
  { id: "INV-0902", number: "MAD-ZAY-2026-0902", student: "ملك حسام الدين", parent: "حسام الدين", branch: "الشيخ زايد", course: "روبوتكس مستوى 1", total: 3900, collected: 0, due: "30 سبتمبر" },
];
const INITIAL_EXPENSES: Expense[] = [
  { id: "EXP-104", description: "مستلزمات روبوتكس للمجموعات الجديدة", branch: "مدينة نصر", category: "مواد ومستلزمات", amount: 3850, date: "24 سبتمبر", status: "approved", createdBy: "أحمد محمود" },
  { id: "EXP-103", description: "صيانة أجهزة معمل البرمجة", branch: "المعادي", category: "تشغيل وصيانة", amount: 1650, date: "23 سبتمبر", status: "pending", createdBy: "سارة خالد" },
  { id: "EXP-102", description: "مكافأة تدريب مسابقة سبتمبر", branch: "الشيخ زايد", category: "مسابقات", amount: 2400, date: "22 سبتمبر", status: "pending", createdBy: "أحمد محمود" },
  { id: "EXP-101", description: "اشتراك خدمة غير معتمد", branch: "مدينة نصر", category: "أخرى", amount: 900, date: "21 سبتمبر", status: "rejected", createdBy: "سارة خالد", reason: "المرفق لا يطابق سياسة المصروفات." },
];
const STATUS_LABEL: Record<InvoiceStatus, string> = { partial: "مدفوعة جزئيًا", overdue: "متأخرة", paid: "مدفوعة", unpaid: "غير مدفوعة" };
const EXPENSE_LABEL: Record<ExpenseStatus, string> = { pending: "بانتظار الاعتماد", approved: "معتمد", rejected: "مرفوض" };
function money(value: number) { return new Intl.NumberFormat("en-US").format(value); }
function invoiceStatus(invoice: Invoice): InvoiceStatus { if (invoice.collected >= invoice.total) return "paid"; if (invoice.collected === 0 && invoice.due.includes("20")) return "overdue"; return invoice.collected > 0 ? "partial" : "unpaid"; }

export default function FinanceDesk() {
  const [, navigate] = useLocation();
  const [view, setView] = useState<View>("overview");
  const [mobileOpen, setMobileOpen] = useState(false);
  const [branch, setBranch] = useState("كل الفروع");
  const [query, setQuery] = useState("");
  const [expenses, setExpenses] = useState(INITIAL_EXPENSES);
  const [paymentInvoice, setPaymentInvoice] = useState(INVOICES[0].id);
  const [paymentAmount, setPaymentAmount] = useState("");
  const [expenseDescription, setExpenseDescription] = useState("");
  const [expenseAmount, setExpenseAmount] = useState("");
  const [expenseBranch, setExpenseBranch] = useState("مدينة نصر");
  const [rejecting, setRejecting] = useState<string | null>(null);
  const [rejectReason, setRejectReason] = useState("");
  const scopedInvoices = INVOICES.filter(item => branch === "كل الفروع" || item.branch === branch);
  const scopedExpenses = expenses.filter(item => branch === "كل الفروع" || item.branch === branch);
  const filteredInvoices = scopedInvoices.filter(item => !query.trim() || `${item.number} ${item.student} ${item.parent}`.toLocaleLowerCase("ar").includes(query.trim().toLocaleLowerCase("ar")));
  const filteredExpenses = scopedExpenses.filter(item => !query.trim() || `${item.description} ${item.createdBy} ${item.category}`.toLocaleLowerCase("ar").includes(query.trim().toLocaleLowerCase("ar")));
  const collected = scopedInvoices.reduce((sum, item) => sum + item.collected, 0);
  const outstanding = scopedInvoices.reduce((sum, item) => sum + item.total - item.collected, 0);
  const approvedExpenses = scopedExpenses.filter(item => item.status === "approved").reduce((sum, item) => sum + item.amount, 0);
  const pendingCount = scopedExpenses.filter(item => item.status === "pending").length;
  const net = collected - approvedExpenses;
  const selectView = (next: View) => { setView(next); setMobileOpen(false); setQuery(""); };
  const recordPayment = (event: FormEvent) => { event.preventDefault(); const amount = Number(paymentAmount); if (!amount || amount <= 0) { toast.error("أدخل مبلغ تحصيل صحيح"); return; } toast.success("تم تسجيل التحصيل للمراجعة", { description: `${money(amount)} ج.م · سيظهر في سجل التحصيل بعد الربط بالخادم.` }); setPaymentAmount(""); };
  const createExpense = (event: FormEvent) => { event.preventDefault(); const amount = Number(expenseAmount); if (!expenseDescription.trim() || !amount || amount <= 0) { toast.error("أدخل وصف المصروف والمبلغ"); return; } setExpenses(current => [{ id: `EXP-${current.length + 110}`, description: expenseDescription, branch: expenseBranch, category: "تشغيل وصيانة", amount, date: "اليوم", status: "pending", createdBy: "المحاسب" }, ...current]); toast.success("تم رفع المصروف للمراجعة", { description: "لن يدخل الإجماليات المعتمدة قبل قرار الاعتماد." }); setExpenseDescription(""); setExpenseAmount(""); };
  const rejectExpense = (event: FormEvent) => { event.preventDefault(); if (!rejecting || !rejectReason.trim()) { toast.error("سبب الرفض إلزامي"); return; } setExpenses(current => current.map(item => item.id === rejecting ? { ...item, status: "rejected", reason: rejectReason } : item)); toast.success("تم رفض المصروف بسبب موثق"); setRejecting(null); setRejectReason(""); };
  return <RoleDashboardShell className="app-shell finance-desk-shell" roleCode="R06" roleLabel="المحاسب" scopeLevel="platform" scopeLabel="المالية والفروع المصرح بها" tenantName="أكاديمية مدى" branchName="كل الفروع">
    {mobileOpen && <button className="mobile-scrim" aria-label="إغلاق القائمة" onClick={() => setMobileOpen(false)} />}
    <aside className={`sidebar ${mobileOpen ? "sidebar-open" : ""}`}><div className="sidebar-top"><button className="finance-desk-brand" onClick={() => navigate("/finance")}><strong>مدى</strong><small>المالية والتحصيل · R06</small></button><button className="icon-button sidebar-close" aria-label="إغلاق القائمة" onClick={() => setMobileOpen(false)}><X size={19} /></button></div><div className="academy-switcher"><span className="academy-avatar"><Wallet size={20} /></span><span className="academy-meta"><strong>أكاديمية مدى</strong><small>أحمد محمود · مالي</small></span></div><div className="nav-caption">المساحة المالية</div><nav className="primary-nav"><NavButton active={view === "overview"} onClick={() => selectView("overview")} icon={<LayoutDashboard size={19} />} label="ملخص مالي" /><NavButton active={view === "collections"} onClick={() => selectView("collections")} icon={<CreditCard size={19} />} label="الفواتير والتحصيل" count={scopedInvoices.length} /><NavButton active={view === "expenses"} onClick={() => selectView("expenses")} icon={<TrendingDown size={19} />} label="المصاريف" count={pendingCount} /><NavButton active={view === "reports"} onClick={() => selectView("reports")} icon={<BarChart3 size={19} />} label="التقارير" /></nav><div className="nav-caption nav-caption-spaced">روابط أخرى</div><nav className="primary-nav"><button className="nav-link" onClick={() => navigate("/academy-owner")}><ShieldCheck size={19} /><span>مراجعة الإدارة</span></button><button className="nav-link" onClick={() => navigate("/approvals")}><FileCheck2 size={19} /><span>الموافقات</span></button></nav><div className="sidebar-spacer" /><div className="sidebar-help"><span className="help-icon"><CircleHelp size={18} /></span><div><strong>محتاج مساعدة؟</strong><span>سياسة التصحيح والمصروفات</span></div><ChevronLeft size={16} /></div><div className="sidebar-bottom"><button className="nav-link" onClick={() => toast("الإعدادات قيد التجهيز")}><Settings size={19} /><span>الإعدادات</span></button><button className="nav-link" onClick={() => toast("تم تسجيل الخروج التجريبي")}><LogOut size={19} /><span>تسجيل الخروج</span></button></div></aside>
    <main className="main-panel"><header className="topbar"><div className="topbar-right"><button className="icon-button mobile-menu-button" aria-label="فتح القائمة" onClick={() => setMobileOpen(true)}><Menu size={21} /></button><label className="finance-branch-select"><MapPin size={16} /><select value={branch} onChange={event => setBranch(event.target.value)}><option>كل الفروع</option><option>مدينة نصر</option><option>المعادي</option><option>الشيخ زايد</option></select></label></div><span className="finance-desk-scope"><ShieldCheck size={14} /> فصل الإنشاء عن الاعتماد</span></header><div className="workspace finance-desk-content"><PageHeader className="welcome-row" copyClassName="welcome-copy" actionsClassName="welcome-actions" eyebrow={<span className="eyebrow"><i className="eyebrow-dot" /> المالية والتحصيل · R06</span>} title={VIEW_TITLES[view]} description={VIEW_COPY[view]} actions={<span className="finance-desk-date"><CalendarDays size={14} /> سبتمبر 2026 · {branch}</span>} /><RoleScopeCard className="finance-desk-scope-card" /><div className="finance-desk-banner"><ShieldCheck size={15} /><span><strong>قاعدة مالية:</strong> الفاتورة المحصلة لا تعدّل مباشرة، والمصروف المرفوض لا يدخل الإجماليات المعتمدة. كل قرار يحتفظ بسبب وسجل.</span></div>{view === "overview" && <Overview collected={collected} outstanding={outstanding} expenses={approvedExpenses} net={net} pending={pendingCount} onCollections={() => selectView("collections")} onExpenses={() => selectView("expenses")} onReports={() => selectView("reports")} />}{view === "collections" && <Collections invoices={filteredInvoices} query={query} setQuery={setQuery} paymentInvoice={paymentInvoice} setPaymentInvoice={setPaymentInvoice} amount={paymentAmount} setAmount={setPaymentAmount} onSubmit={recordPayment} />}{view === "expenses" && <Expenses expenses={filteredExpenses} query={query} setQuery={setQuery} description={expenseDescription} setDescription={setExpenseDescription} amount={expenseAmount} setAmount={setExpenseAmount} branch={expenseBranch} setBranch={setExpenseBranch} onSubmit={createExpense} onReject={setRejecting} />}{view === "reports" && <Reports invoices={scopedInvoices} expenses={scopedExpenses} collected={collected} approvedExpenses={approvedExpenses} net={net} />}</div></main>{rejecting && <div className="finance-desk-modal-backdrop"><form className="finance-desk-modal" onSubmit={rejectExpense}><button type="button" className="finance-modal-close" onClick={() => setRejecting(null)}><X size={16} /></button><span className="finance-modal-icon"><AlertCircle size={19} /></span><h2>رفض المصروف</h2><p>سبب الرفض إلزامي وسيظهر في سجل المصروف.</p><textarea value={rejectReason} onChange={event => setRejectReason(event.target.value)} placeholder="اكتب سببًا واضحًا للرفض..." rows={4} /><button className="finance-desk-primary" type="submit"><Check size={15} /> حفظ الرفض</button></form></div>}</RoleDashboardShell>;
}
function NavButton({ active, onClick, icon, label, count }: { active: boolean; onClick: () => void; icon: ReactNode; label: string; count?: number }) { return <button className={`nav-link ${active ? "active" : ""}`} onClick={onClick}>{icon}<span>{label}</span>{count !== undefined && <span className="nav-count">{count}</span>}</button>; }
const VIEW_TITLES: Record<View, string> = { overview: "الملخص المالي", collections: "الفواتير والتحصيل", expenses: "المصاريف", reports: "التقارير المالية" };
const VIEW_COPY: Record<View, string> = { overview: "تابع التحصيل والمستحقات والمصروفات المعتمدة قبل اتخاذ الخطوة التالية.", collections: "سجل الدفعات، راجع الأرصدة، وارفع طلب تصحيح بدل تعديل الفاتورة مباشرة.", expenses: "أنشئ مصروفًا، راجع حالته، وارفضه بسبب موثق قبل دخوله في الإجماليات.", reports: "قارن التحصيل بالمصروفات المعتمدة وصافي الحركة حسب الفروع." };
function Overview({ collected, outstanding, expenses, net, pending, onCollections, onExpenses, onReports }: { collected: number; outstanding: number; expenses: number; net: number; pending: number; onCollections: () => void; onExpenses: () => void; onReports: () => void }) { return <><section className="finance-desk-kpis"><Kpi icon={<TrendingUp size={16} />} label="إجمالي التحصيل" value={`${money(collected)} ج.م`} hint="كل الفروع · هذا الشهر" tone="teal" /><Kpi icon={<Clock3 size={16} />} label="المستحقات" value={`${money(outstanding)} ج.م`} hint="فواتير لم تكتمل" tone="amber" /><Kpi icon={<TrendingDown size={16} />} label="مصروفات معتمدة" value={`${money(expenses)} ج.م`} hint="لا تشمل pending/rejected" tone="blue" /><Kpi icon={<Wallet size={16} />} label="صافي الحركة" value={`${money(net)} ج.م`} hint={`${pending} مصروفات تنتظر القرار`} tone="violet" /></section><div className="finance-desk-grid"><section className="finance-desk-panel"><PanelTitle icon={<FileCheck2 size={16} />} title="الخطوة التالية" /><div className="finance-next-list"><button onClick={onCollections}><span className="finance-next-icon amber"><CreditCard size={15} /></span><span><strong>راجع الفواتير غير المكتملة</strong><small>سجل التحصيل أو ارفع طلب التصحيح</small></span><ChevronLeft size={14} /></button><button onClick={onExpenses}><span className="finance-next-icon violet"><TrendingDown size={15} /></span><span><strong>راجع المصروفات المعلقة</strong><small>اعتماد أو رفض بسبب موثق</small></span><ChevronLeft size={14} /></button><button onClick={onReports}><span className="finance-next-icon teal"><BarChart3 size={15} /></span><span><strong>افتح تقرير الفروع</strong><small>تحصيل · مستحق · مصروف · صافي</small></span><ChevronLeft size={14} /></button></div></section><section className="finance-desk-panel"><PanelTitle icon={<ShieldCheck size={16} />} title="ضوابط الإقفال" /><div className="finance-control-list"><span><CheckCircle2 size={15} /> المحصل يدخل في سجل التحصيل فقط</span><span><CheckCircle2 size={15} /> المصروف pending لا يدخل صافي الحركة</span><span><CheckCircle2 size={15} /> التعديل بعد التحصيل يمر بطلب تصحيح</span><span><CheckCircle2 size={15} /> الرفض يحتاج سببًا إلزاميًا</span></div></section></div></>; }
function Collections({ invoices, query, setQuery, paymentInvoice, setPaymentInvoice, amount, setAmount, onSubmit }: { invoices: Invoice[]; query: string; setQuery: (v: string) => void; paymentInvoice: string; setPaymentInvoice: (v: string) => void; amount: string; setAmount: (v: string) => void; onSubmit: (e: FormEvent) => void }) { return <div className="finance-desk-two-col"><section className="finance-desk-panel"><PanelTitle icon={<CreditCard size={16} />} title="الفواتير والأرصدة" action={<label className="finance-desk-search"><Search size={13} /><input value={query} onChange={event => setQuery(event.target.value)} placeholder="فاتورة أو طالب..." /></label>} /><div className="finance-invoice-list">{invoices.map(invoice => { const status = invoiceStatus(invoice); return <article className="finance-invoice-row" key={invoice.id}><div className="finance-invoice-person"><span>{invoice.student.slice(0, 1)}</span><div><strong>{invoice.student}</strong><small>{invoice.number} · {invoice.parent}</small></div></div><div className="finance-invoice-meta"><span>{invoice.course} · {invoice.branch}</span><small>استحقاق {invoice.due}</small></div><div className="finance-invoice-money"><strong>{money(invoice.total)} ج.م</strong><small>محصل {money(invoice.collected)} · متبقي {money(invoice.total - invoice.collected)}</small></div><span className={`finance-desk-status ${status}`}>{STATUS_LABEL[status]}</span></article>; })}</div></section><section className="finance-desk-panel finance-payment-card"><PanelTitle icon={<Wallet size={16} />} title="تسجيل تحصيل" action={<span className="finance-desk-context"><ShieldCheck size={13} /> R06</span>} /><form onSubmit={onSubmit} className="finance-desk-form"><label>الفاتورة<select value={paymentInvoice} onChange={event => setPaymentInvoice(event.target.value)}>{INVOICES.filter(item => item.collected < item.total).map(item => <option key={item.id} value={item.id}>{item.number} · {item.student}</option>)}</select></label><label>المبلغ (ج.م)<input value={amount} onChange={event => setAmount(event.target.value)} type="number" min="1" placeholder="مثال: 1200" /></label><label>طريقة الدفع<select><option>نقدي</option><option>بطاقة</option><option>تحويل بنكي</option></select></label><button className="finance-desk-primary" type="submit"><Check size={14} /> تسجيل التحصيل</button><p><AlertCircle size={13} /> التسجيل تجريبي؛ الفاتورة المحصلة لا تعدّل مباشرة.</p></form></section></div>; }
function Expenses({ expenses, query, setQuery, description, setDescription, amount, setAmount, branch, setBranch, onSubmit, onReject }: { expenses: Expense[]; query: string; setQuery: (v: string) => void; description: string; setDescription: (v: string) => void; amount: string; setAmount: (v: string) => void; branch: string; setBranch: (v: string) => void; onSubmit: (e: FormEvent) => void; onReject: (id: string) => void }) { return <div className="finance-desk-two-col"><section className="finance-desk-panel"><PanelTitle icon={<TrendingDown size={16} />} title="سجل المصروفات" action={<label className="finance-desk-search"><Search size={13} /><input value={query} onChange={event => setQuery(event.target.value)} placeholder="ابحث في المصروفات..." /></label>} /><div className="finance-expense-list">{expenses.map(expense => <article className="finance-expense-row" key={expense.id}><span className={`finance-expense-icon ${expense.status}`}><FileText size={15} /></span><div><strong>{expense.description}</strong><small>{expense.id} · {expense.category} · {expense.branch} · {expense.date}</small></div><strong>{money(expense.amount)} ج.م</strong><span className={`finance-desk-status ${expense.status}`}>{EXPENSE_LABEL[expense.status]}</span>{expense.status === "pending" && <button className="finance-reject-link" onClick={() => onReject(expense.id)}>رفض بسبب</button>}{expense.reason && <small className="finance-reason">{expense.reason}</small>}</article>)}</div></section><section className="finance-desk-panel"><PanelTitle icon={<Plus size={16} />} title="إضافة مصروف" action={<span className="finance-desk-context">يبدأ pending</span>} /><form onSubmit={onSubmit} className="finance-desk-form"><label>وصف المصروف<input value={description} onChange={event => setDescription(event.target.value)} placeholder="مثال: صيانة معمل" /></label><label>الفرع<select value={branch} onChange={event => setBranch(event.target.value)}><option>مدينة نصر</option><option>المعادي</option><option>الشيخ زايد</option></select></label><label>التصنيف<select><option>تشغيل وصيانة</option><option>مواد ومستلزمات</option><option>أجور مدربين</option><option>فعاليات</option></select></label><label>المبلغ (ج.م)<input value={amount} onChange={event => setAmount(event.target.value)} type="number" min="1" placeholder="مثال: 1500" /></label><button className="finance-desk-primary" type="submit"><Plus size={14} /> رفع للمراجعة</button><p><ShieldCheck size={13} /> المصروف لا يدخل التقرير قبل الاعتماد.</p></form></section></div>; }
function Reports({ invoices, expenses, collected, approvedExpenses, net }: { invoices: Invoice[]; expenses: Expense[]; collected: number; approvedExpenses: number; net: number }) { const branches = ["مدينة نصر", "المعادي", "الشيخ زايد"]; return <section className="finance-desk-panel"><PanelTitle icon={<BarChart3 size={16} />} title="تقرير الحركة المالية" action={<button className="finance-desk-secondary" onClick={() => toast.success("تم تجهيز تصدير التقرير التجريبي")}><ArrowDownToLine size={14} /> تصدير التقرير</button>} /><div className="finance-report-summary"><span><small>التحصيل</small><strong>{money(collected)} ج.م</strong></span><span><small>المصروف المعتمد</small><strong>{money(approvedExpenses)} ج.م</strong></span><span><small>صافي الحركة</small><strong>{money(net)} ج.م</strong></span></div><div className="finance-branch-report">{branches.map(branch => { const branchInvoices = invoices.filter(item => item.branch === branch); const branchExpenses = expenses.filter(item => item.branch === branch && item.status === "approved").reduce((sum, item) => sum + item.amount, 0); const branchCollected = branchInvoices.reduce((sum, item) => sum + item.collected, 0); return <article key={branch}><div><strong>{branch}</strong><small>{branchInvoices.length} فواتير · {expenses.filter(item => item.branch === branch).length} مصروفات</small></div><span><small>تحصيل</small><b>{money(branchCollected)}</b></span><span><small>مصروف معتمد</small><b>{money(branchExpenses)}</b></span><span><small>صافي</small><b>{money(branchCollected - branchExpenses)}</b></span></article>; })}</div><div className="finance-report-note"><ShieldCheck size={14} /> التقرير يستبعد المصروفات pending وrejected من الصافي المعتمد.</div></section>; }
function Kpi({ icon, label, value, hint, tone }: { icon: ReactNode; label: string; value: ReactNode; hint: string; tone: string }) { return <article className="finance-desk-kpi"><span className={`finance-desk-kpi-icon ${tone}`}>{icon}</span><small>{label}</small><strong>{value}</strong><span>{hint}</span></article>; }
function PanelTitle({ icon, title, action }: { icon: ReactNode; title: string; action?: ReactNode }) { return <div className="finance-desk-panel-title"><div><span>{icon}</span><h2>{title}</h2></div>{action}</div>; }
