export type PageKind = 'dashboard' | 'table' | 'workflow' | 'portal' | 'hub';
export interface MetricCard { label: string; value: string; trend: string; tone: 'teal' | 'blue' | 'amber' | 'rose'; }
export interface PageDefinition { path: string; title: string; kicker: string; description: string; kind: PageKind; metrics: readonly MetricCard[]; columns: readonly string[]; rows: readonly string[][]; actions: readonly string[]; }

const page = (path: string, title: string, kicker: string, description: string, kind: PageKind, metrics: readonly MetricCard[], columns: readonly string[], rows: readonly string[][], actions: readonly string[]): PageDefinition => ({ path, title, kicker, description, kind, metrics, columns, rows, actions });
const m = (label: string, value: string, trend: string, tone: MetricCard['tone']): MetricCard => ({ label, value, trend, tone });

export const PAGE_CATALOG: readonly PageDefinition[] = [
  page('/', 'ملخص التشغيل', 'BRANCH OPERATIONS', 'صورة يومية سريعة للفرع: الحضور، الجلسات، الموافقات، والتنبيهات التي تحتاج قرارًا.', 'dashboard', [m('جلسات اليوم', '24', '+8% عن أمس', 'teal'), m('نسبة الحضور', '92%', '+4.2%', 'blue'), m('في انتظار قرار', '7', '3 حرجة', 'amber'), m('تنبيهات تشغيلية', '3', 'تحتاج متابعة', 'rose')], ['المؤشر', 'القيمة', 'الحالة'], [['حضور اليوم', '92%', 'مستقر'], ['جلسات تبدأ قريبًا', '6', 'مراقبة'], ['طلبات تحتاج اعتماد', '7', 'قرار مطلوب'], ['تعارضات الجدول', '2', 'تصعيد']], ['فتح جدول اليوم', 'مراجعة الموافقات']),
  page('/workspace', 'Workspace Hub', 'ROLE DIRECTORY', 'نقطة دخول واحدة لمراجعة شجرة الأدوار ومساحات العمل المرتبطة بها.', 'hub', [m('الأدوار', '10', 'R00 → R09', 'teal'), m('مساحات العمل', '23', 'مسارات معرفة', 'blue'), m('Scopes', '8', 'مستويات', 'amber'), m('Consumers', '2', 'R08 / R09', 'rose')], ['Role', 'Identity', 'Scope', 'Home'], [['R00', 'Staff', 'Platform', '/platform-console'], ['R01–R07', 'Staff', 'Operational', 'Role dashboards'], ['R08', 'Consumer', 'Family', '/family-portal'], ['R09', 'Consumer', 'Self', '/student-portal']], ['استعراض كل الأدوار', 'فتح الـRole الحالي']),
  page('/platform-console', 'مركز المنصة', 'PLATFORM CONSOLE · R00', 'إدارة tenants والخطط وطلبات الدعم مع إبقاء البيانات الحساسة خلف support exception مدقق.', 'dashboard', [m('Academies', '18', '+2 هذا الشهر', 'teal'), m('Active plans', '15', '83% healthy', 'blue'), m('Support queue', '6', '2 escalated', 'amber'), m('Exceptions', '1', 'ينتهي اليوم', 'rose')], ['الأكاديمية', 'الخطة', 'الحالة'], [['Mada West', 'Growth', 'Active'], ['Mada East', 'Starter', 'Review'], ['New tenant', 'Trial', 'Onboarding'], ['Support exception', 'Temporary', 'Expires today']], ['إضافة أكاديمية', 'مراجعة الاستثناءات']),
  page('/executive-dashboard', 'اللوحة التنفيذية', 'ACADEMY ROLLUP · R01', 'ملخص على مستوى الأكاديمية يساعد مسؤولها على متابعة الفروع والفرق والنتائج.', 'dashboard', [m('الفروع', '6', 'كلها active', 'teal'), m('طلاب نشطون', '1,284', '+11%', 'blue'), m('إيراد الشهر', 'EGP 420K', '+8.6%', 'amber'), m('Tickets', '12', '4 تحتاج قرار', 'rose')], ['المحور', 'النتيجة', 'الاتجاه'], [['Retention', '88%', 'صاعد'], ['Attendance', '94%', 'مستقر'], ['Revenue', 'EGP 420K', 'صاعد'], ['Open decisions', '4', 'يحتاج مراجعة']], ['مراجعة الفروع', 'فتح التقرير التنفيذي']),
  page('/academy-owner', 'إدارة الأكاديمية', 'ACADEMY MANAGEMENT · R01', 'إدارة الفروع والفريق والتذاكر في نطاق الأكاديمية بالكامل.', 'table', [m('Branches', '6', '2 تحتاج تحديث', 'teal'), m('Team members', '74', '+5', 'blue'), m('Open tickets', '12', '4 high priority', 'amber'), m('Pending invites', '8', 'هذا الأسبوع', 'rose')], ['الفرع', 'المدير', 'الفريق', 'الحالة'], [['مدينة نصر', 'أحمد سامي', '18', 'Healthy'], ['المعادي', 'سارة علي', '13', 'Healthy'], ['الشيخ زايد', 'عمر حسن', '11', 'Needs review'], ['التجمع', '—', '9', 'Manager invite']], ['إضافة فرع', 'دعوة مدير فرع']),
  page('/branch-operations', 'تشغيل الفرع', 'BRANCH CONTROL · R02', 'مركز الفرق والجدول والتعارضات وقرارات التشغيل اليومية داخل الفرع.', 'workflow', [m('Staff on duty', '18', '3 substitutes', 'teal'), m('Schedule load', '86%', 'منظم', 'blue'), m('Conflicts', '2', '1 critical', 'amber'), m('Approvals', '7', 'في الطابور', 'rose')], ['الطلب', 'من', 'الأثر', 'الحالة'], [['تبديل جلسة', 'Instructor 04', 'Session 10:00', 'Pending'], ['تعارض غرفة', 'Group A / B', 'Room 2', 'Escalated'], ['تحديث فريق', 'Head Instructor', 'Team roster', 'Ready'], ['إغلاق يوم', 'Secretary', 'Daily close', 'Review']], ['حل التعارضات', 'فتح طابور القرارات']),
  page('/head-instructors', 'ملخص الفريق', 'QUALITY & TEAM · R03', 'متابعة جودة المدربين وقائمة المراجعة والـsessions التي تقع في نطاق الإشراف.', 'dashboard', [m('المدربون', '14', '2 onboarding', 'teal'), m('Evaluations', '38', '9 تحتاج review', 'blue'), m('Quality score', '4.6/5', '+0.2', 'amber'), m('Escalations', '3', 'هذا الأسبوع', 'rose')], ['الفريق', 'Quality', 'مراجعات', 'الحالة'], [['Team Alpha', '4.8/5', '2', 'Healthy'], ['Team Beta', '4.5/5', '5', 'Review'], ['New instructors', '—', '2', 'Onboarding'], ['Escalated cases', '—', '3', 'Action']], ['مراجعة الجودة', 'فتح جدول الفريق']),
  page('/academic-programs', 'البرامج الأكاديمية', 'CURRICULUM · R03', 'إدارة البرامج ومستويات التقدم ومراجعة curriculum ضمن نطاق الفريق.', 'table', [m('Programs', '12', '3 active tracks', 'teal'), m('Groups', '32', '+4', 'blue'), m('Progress reviews', '18', 'هذا الأسبوع', 'amber'), m('At risk', '5', 'يحتاج تدخل', 'rose')], ['البرنامج', 'المجموعات', 'Progress', 'الحالة'], [['English Juniors', '8', '87%', 'On track'], ['Math Foundations', '6', '79%', 'Review'], ['Coding Kids', '5', '92%', 'Strong'], ['Arabic Reading', '4', '68%', 'At risk']], ['إضافة برنامج', 'فتح مراجعة التقدم']),
  page('/instructor-desk', 'مكتب المدرب', 'INSTRUCTOR DESK · R04', 'اليوم الخاص بالمدرب: الجلسات، الحضور، التقييم، والطلاب المسندون.', 'workflow', [m('جلسات اليوم', '5', 'التالية 10:00', 'teal'), m('حضور مسجل', '3/5', 'جلسات متبقية', 'blue'), m('Evaluations', '4', 'مسودة', 'amber'), m('Students', '28', 'assigned scope', 'rose')], ['الجلسة', 'المجموعة', 'الحضور', 'التقييم'], [['10:00', 'Juniors A', 'Pending', 'Draft'], ['12:00', 'Math B', 'Complete', 'Submitted'], ['15:00', 'Coding C', 'Upcoming', '—'], ['17:00', 'Juniors A', 'Upcoming', '—']], ['تسجيل الحضور', 'إكمال التقييم']),
  page('/instructor', 'مساحتي الأكاديمية', 'MY ACADEMIC SPACE · R04', 'قائمة الطلاب المسندين وتقدمهم وملاحظات المتابعة الخاصة بالمدرب.', 'table', [m('Assigned students', '28', '4 need attention', 'teal'), m('Avg progress', '81%', '+3%', 'blue'), m('Open notes', '9', 'هذا الأسبوع', 'amber'), m('Achievements', '16', 'جديد', 'rose')], ['الطالب', 'المسار', 'Progress', 'آخر متابعة'], [['سلمى محمود', 'Juniors A', '92%', 'اليوم'], ['يوسف علي', 'Math B', '76%', 'أمس'], ['ليان أحمد', 'Coding C', '84%', 'منذ يومين'], ['عمر حسن', 'Juniors A', '68%', 'مطلوب متابعة']], ['إضافة ملاحظة', 'فتح بطاقة الطالب']),
  page('/secretary-desk', 'مكتب الخدمة', 'SERVICE DESK · R05', 'تحويل الـleads إلى تسجيلات مؤكدة مع متابعة التكرار والـhandoff.', 'workflow', [m('New leads', '34', '+12 today', 'teal'), m('Follow-ups', '18', '6 overdue', 'blue'), m('Enrollments', '9', 'هذا الأسبوع', 'amber'), m('Duplicates', '3', 'تحتاج دمج', 'rose')], ['Lead', 'المصدر', 'المرحلة', 'الإجراء'], [['مريم خالد', 'Instagram', 'New', 'Contact'], ['محمد عادل', 'Referral', 'Qualified', 'Schedule'], ['نور أحمد', 'Website', 'Enrolled', 'Handoff'], ['Unknown phone', 'Campaign', 'Duplicate', 'Merge']], ['إضافة lead', 'فتح طابور التسجيل']),
  page('/secretary', 'تسجيلات السكرتارية', 'ENROLLMENT · R05', 'سجل التسجيلات والمتابعة ونقل الطالب من lead إلى المجموعة المناسبة.', 'table', [m('Applications', '22', 'هذا الشهر', 'teal'), m('Confirmed', '15', '68%', 'blue'), m('Waiting docs', '4', 'متابعة', 'amber'), m('Handoffs', '8', 'للفرع', 'rose')], ['الطالب', 'البرنامج', 'المرحلة', 'المسؤول'], [['سارة سامح', 'English', 'Confirmed', 'Secretary 02'], ['كريم وليد', 'Math', 'Documents', 'Secretary 01'], ['جنى عمر', 'Coding', 'Trial', 'Secretary 02'], ['آدم يوسف', 'Juniors', 'Handoff', 'Branch Manager']], ['تأكيد التسجيل', 'تحويل للمجموعة']),
  page('/finance-desk', 'المكتب المالي', 'FINANCE DESK · R06', 'تحصيلات ومصروفات وتقارير المالية داخل النطاق المصرح به.', 'dashboard', [m('Collected', 'EGP 286K', '+12%', 'teal'), m('Outstanding', 'EGP 74K', '18 invoices', 'blue'), m('Expenses', 'EGP 42K', 'هذا الشهر', 'amber'), m('Corrections', '4', 'pending approval', 'rose')], ['المعاملة', 'القيمة', 'المالك', 'الحالة'], [['Invoice #1042', 'EGP 12,500', 'Branch 01', 'Paid'], ['Invoice #1043', 'EGP 8,200', 'Branch 01', 'Pending'], ['Expense #88', 'EGP 1,850', 'Branch 02', 'Review'], ['Correction #12', 'EGP 3,400', 'Branch 01', 'Approval']], ['تسجيل تحصيل', 'فتح التصحيحات']),
  page('/finance', 'الماليات', 'FINANCIAL WORKFLOWS · R06', 'الفواتير والتصحيحات والمصروفات مع فصل واضح بين submit وapprove.', 'workflow', [m('Open invoices', '18', '7 overdue', 'teal'), m('Payments today', '31', 'EGP 18K', 'blue'), m('Expenses queue', '6', '2 escalated', 'amber'), m('Approvals', '4', 'no self-approval', 'rose')], ['العنصر', 'النوع', 'من', 'إلى'], [['Invoice #1043', 'Collection', 'PENDING', '—'], ['Expense #88', 'Expense', 'PENDING', 'APPROVED'], ['Correction #12', 'Correction', 'LOCKED', 'CORRECTION_PENDING'], ['Discount #22', 'Discount', 'SUBMITTED', 'REVIEW']], ['إنشاء فاتورة', 'إرسال للموافقة']),
  page('/marketing-desk', 'مكتب التسويق', 'MARKETING DESK · R07', 'الحملات والمحتوى والـmarketing leads مع ربط واضح بالـhandoff.', 'dashboard', [m('Active campaigns', '7', '2 launching', 'teal'), m('Reach', '84K', '+18%', 'blue'), m('Marketing leads', '46', '9 qualified', 'amber'), m('Content queue', '11', '3 review', 'rose')], ['الحملة', 'القناة', 'Reach', 'الحالة'], [['Back to school', 'Instagram', '32K', 'Active'], ['Parents week', 'Facebook', '18K', 'Review'], ['Coding trial', 'Google', '9K', 'Launching'], ['Organic stories', 'Website', '25K', 'Draft']], ['إنشاء حملة', 'فتح طابور المحتوى']),
  page('/family-portal', 'بوابة الأسرة', 'FAMILY PORTAL · R08', 'عرض آمن ومبسّط للأطفال المرتبطين والحضور والتقييمات والفواتير.', 'portal', [m('الأطفال', '2', 'family scope', 'teal'), m('الحضور', '96%', 'هذا الشهر', 'blue'), m('تقييمات جديدة', '3', 'للمراجعة', 'amber'), m('رصيد مستحق', 'EGP 4,200', 'فاتورتان', 'rose')], ['الطفل', 'المجموعة', 'الحضور', 'آخر تحديث'], [['سلمى محمود', 'Juniors A', '98%', 'اليوم'], ['يوسف علي', 'Math B', '94%', 'أمس'], ['Invoices', '—', '—', '2 pending'], ['Messages', '—', '—', '1 new']], ['عرض التقييمات', 'فتح الفواتير']),
  page('/student-portal', 'مساحة الطالب', 'STUDENT PORTAL · R09', 'مساحة الطالب الشخصية للتعلم والجلسات والتقدم والإنجازات.', 'portal', [m('الجلسات', '4', 'هذا الأسبوع', 'teal'), m('Progress', '82%', '+5%', 'blue'), m('Achievements', '12', '2 جديد', 'amber'), m('Next session', 'غدًا', '10:00', 'rose')], ['المادة', 'التقدم', 'الجلسة القادمة', 'الحالة'], [['English', '92%', 'غدًا 10:00', 'On track'], ['Math', '78%', 'الخميس 16:00', 'Practice'], ['Coding', '84%', 'السبت 12:00', 'Strong'], ['Achievements', '12', '—', 'New']], ['فتح الدرس', 'عرض الإنجازات']),
  page('/students', 'الطلاب', 'STUDENT RECORDS', 'سجل الطلاب التشغيلي مع البحث والتصفية وبيانات النطاق الحالي.', 'table', [m('Total students', '1,284', '+46 هذا الشهر', 'teal'), m('Active', '1,112', '87%', 'blue'), m('New', '46', 'هذا الشهر', 'amber'), m('At risk', '24', 'مراجعة', 'rose')], ['الطالب', 'الفرع', 'المجموعة', 'الحالة'], [['سلمى محمود', 'مدينة نصر', 'Juniors A', 'Active'], ['يوسف علي', 'المعادي', 'Math B', 'Active'], ['ليان أحمد', 'التجمع', 'Coding C', 'Review'], ['عمر حسن', 'مدينة نصر', 'Juniors A', 'At risk']], ['إضافة طالب', 'تصدير النطاق']),
  page('/classes', 'الحصص والكورسات', 'CLASSES & GROUPS', 'المجموعات والكورسات ومقاعدها والمدرب المسؤول عنها.', 'table', [m('Courses', '42', '6 programs', 'teal'), m('Groups', '86', '+8', 'blue'), m('Seats used', '78%', 'healthy', 'amber'), m('Conflicts', '2', 'تحتاج حل', 'rose')], ['المجموعة', 'الكورس', 'المدرب', 'المقاعد'], [['Juniors A', 'English', 'مها حسن', '16/18'], ['Math B', 'Math', 'عمر سامي', '14/16'], ['Coding C', 'Coding', 'نور علي', '12/14'], ['Arabic D', 'Arabic', 'سارة خالد', '18/18']], ['إنشاء مجموعة', 'إدارة المقاعد']),
  page('/schedule', 'الجدول والمواعيد', 'SCHEDULE', 'جدول الجلسات والمجموعات مع تعارضات قابلة للمراجعة قبل التأكيد.', 'workflow', [m('Sessions', '148', 'هذا الأسبوع', 'teal'), m('Rooms', '12', '86% utilized', 'blue'), m('Conflicts', '2', '1 critical', 'amber'), m('Substitutes', '3', 'pending', 'rose')], ['الوقت', 'المجموعة', 'الغرفة', 'الحالة'], [['اليوم 10:00', 'Juniors A', 'Room 2', 'Confirmed'], ['اليوم 12:00', 'Math B', 'Room 4', 'Confirmed'], ['اليوم 15:00', 'Coding C', 'Room 2', 'Conflict'], ['غدًا 17:00', 'Arabic D', 'Room 1', 'Substitute']], ['إضافة جلسة', 'حل التعارضات']),
  page('/team', 'الفريق', 'TEAM DIRECTORY', 'دليل الفريق والأدوار والنطاقات وحالة الدعوات والتكليفات.', 'table', [m('Members', '74', '+5', 'teal'), m('Instructors', '46', '62%', 'blue'), m('On duty', '18', 'اليوم', 'amber'), m('Invites', '8', 'pending', 'rose')], ['الاسم', 'الدور', 'النطاق', 'الحالة'], [['أحمد سامي', 'R02 Branch Manager', 'Branch', 'Active'], ['مها حسن', 'R04 Instructor', 'Assigned', 'Active'], ['سارة علي', 'R05 Secretary', 'Branch', 'Active'], ['عمر حسن', 'R04 Instructor', 'Assigned', 'Invite pending']], ['دعوة عضو', 'مراجعة الصلاحيات']),
  page('/approvals', 'الموافقات', 'DECISION QUEUE', 'طابور القرارات مع reason/evidence وفصل مقدم الطلب عن صاحب الاعتماد.', 'workflow', [m('Pending', '7', '3 high priority', 'teal'), m('Approved', '24', 'هذا الشهر', 'blue'), m('Rejected', '3', 'مع reason', 'amber'), m('Escalated', '2', 'R01 review', 'rose')], ['الطلب', 'المقدم', 'القرار', 'الحالة'], [['Expense #88', 'Accountant', 'Branch Manager', 'Pending'], ['Schedule swap', 'Instructor', 'Branch Manager', 'Pending'], ['Discount #22', 'Secretary', 'Academy Owner', 'Escalated'], ['Correction #12', 'Accountant', 'Academy Owner', 'Approved']], ['مراجعة الطلب', 'تصعيد الطلب']),
  page('/reports', 'التقارير', 'SCOPED REPORTS', 'تقارير محكومة بالنطاق مع masking وتصدير مدقق.', 'dashboard', [m('Saved reports', '18', '6 shared', 'teal'), m('Attendance', '94%', 'stable', 'blue'), m('Revenue', 'EGP 420K', '+8.6%', 'amber'), m('Exports', '9', 'هذا الشهر', 'rose')], ['التقرير', 'النطاق', 'آخر تحديث', 'الوصول'], [['Executive rollup', 'Academy', 'اليوم', 'R01'], ['Branch attendance', 'Branch 01', 'أمس', 'R02'], ['Finance summary', 'Branch 01', 'أمس', 'R06'], ['Family report', 'Family', 'اليوم', 'R08']], ['إنشاء تقرير', 'تصدير النطاق']),
];

export function getPageDefinition(path: string): PageDefinition {
  return PAGE_CATALOG.find((pageDefinition) => pageDefinition.path === path) ?? PAGE_CATALOG[0];
}
