import { ArrowDown, ArrowLeft, ArrowUpLeft, BarChart3, CircleCheck, Menu, Send, Sparkles, Target, Users, X } from "lucide-react";
import { FormEvent, useEffect, useState } from "react";
import { Link } from "wouter";
import { DASHBOARD_URL, submitPublicLead } from "@/lib/publicApi";

type FormMessage = { type: "success" | "error"; text: string } | null;

function DemoForm() {
  const [message, setMessage] = useState<FormMessage>(null);
  const [pending, setPending] = useState(false);
  const handleSubmit = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); setMessage(null); setPending(true); const formElement = event.currentTarget; const form = new FormData(formElement); try { await submitPublicLead({ kind: "demo", name: String(form.get("name")), email: String(form.get("email")), phone: String(form.get("phone")), company: String(form.get("company")), teamSize: String(form.get("teamSize")), trainingNeed: String(form.get("trainingNeed")) }); formElement.reset(); setMessage({ type: "success", text: "وصل طلبك. سيتواصل معك فريق Mada Academy خلال يوم عمل." }); } catch (error) { setMessage({ type: "error", text: error instanceof Error ? error.message : "تعذر إرسال الطلب. حاول مرة أخرى." }); } finally { setPending(false); } };
  return <form className="lead-form" onSubmit={handleSubmit}><div className="form-heading"><span>01</span><div><strong>اطلب Demo لفريقك</strong><small>سنريك كيف تتحول الأولويات إلى مسار تعلم قابل للقياس.</small></div></div><div className="field-grid"><label>الاسم الكامل<input required name="name" placeholder="مثال: سارة أحمد" /></label><label>البريد المهني<input required type="email" name="email" placeholder="you@company.com" dir="ltr" /></label><label>رقم الهاتف<input required name="phone" type="tel" placeholder="01xxxxxxxxx" dir="ltr" /></label><label>الجهة / الشركة<input required name="company" placeholder="اسم الجهة" /></label><label>حجم الفريق<select required name="teamSize" defaultValue=""><option value="" disabled>اختر الحجم</option><option>1–20</option><option>21–100</option><option>101–500</option><option>500+</option></select></label></div><label>ما الأولوية التي تريد تحسينها؟<textarea required name="trainingNeed" rows={3} placeholder="مثال: نريد رفع جاهزية قادة الصف الأول…" /></label><button className="button button-primary button-wide" disabled={pending}>{pending ? "جارٍ إرسال الطلب…" : "أرسل طلب الـ Demo"}<Send size={17} /></button>{message && <p className={`form-message ${message.type}`}><CircleCheck size={16} />{message.text}</p>}</form>;
}

function RegistrationForm() {
  const [message, setMessage] = useState<FormMessage>(null);
  const [pending, setPending] = useState(false);
  const handleSubmit = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); setMessage(null); setPending(true); const formElement = event.currentTarget; const form = new FormData(formElement); try { await submitPublicLead({ kind: "registration", name: String(form.get("name")), email: String(form.get("email")), phone: String(form.get("phone")), track: String(form.get("track")) as "individual" | "team", goal: String(form.get("goal")) }); formElement.reset(); setMessage({ type: "success", text: "تم تسجيل اهتمامك. سنرسل لك الخطوة التالية قريبًا." }); } catch (error) { setMessage({ type: "error", text: error instanceof Error ? error.message : "تعذر إتمام التسجيل. حاول مرة أخرى." }); } finally { setPending(false); } };
  return <form className="registration-form" onSubmit={handleSubmit}><div className="form-heading"><span>02</span><div><strong>سجّل اهتمامك</strong><small>للأفراد والفرق التي تريد أن تبدأ بخطوة واضحة.</small></div></div><label>الاسم الكامل<input required name="name" placeholder="اسمك" /></label><label>البريد الإلكتروني<input required type="email" name="email" placeholder="you@email.com" dir="ltr" /></label><label>رقم الهاتف<input required name="phone" type="tel" placeholder="01xxxxxxxxx" dir="ltr" /></label><label>أنا هنا بصفتي<select required name="track" defaultValue="individual"><option value="individual">فردًا أريد تطوير مساري</option><option value="team">قائد فريق أريد تطوير فريقي</option></select></label><label>ما النتيجة التي تطمح لها؟<textarea required name="goal" rows={3} placeholder="اكتب النتيجة التي تريد الوصول إليها…" /></label><button className="button button-dark button-wide" disabled={pending}>{pending ? "جارٍ التسجيل…" : "احجز مقعدك في المسار التالي"}<ArrowLeft size={17} /></button>{message && <p className={`form-message ${message.type}`}><CircleCheck size={16} />{message.text}</p>}</form>;
}

const audiences = [{ icon: Target, label: "للـ HR", title: "تعلم يثبت أثره أمام الإدارة", text: "حوّل برامج التطوير من نشاط منفصل إلى لغة نتائج يفهمها كل أصحاب القرار." }, { icon: Users, label: "للقادة", title: "قادة يتقدمون بالفعل لا بالحضور", text: "مسارات عملية تساعد القائد على ممارسة السلوك الجديد في سياق عمله الحقيقي." }, { icon: Sparkles, label: "للأفراد", title: "خطوة مهنية تالية أوضح", text: "ابنِ مهارة تفتح لك مساحة جديدة، مع إيقاع تعلم يناسب عملك وطموحك." }];

export default function Home() {
  const [menuOpen, setMenuOpen] = useState(false);
  useEffect(() => {
    const sections = Array.from(document.querySelectorAll<HTMLElement>(".reveal-on-scroll"));
    const observer = new IntersectionObserver(entries => entries.forEach(entry => {
      if (entry.isIntersecting) observer.unobserve(entry.target);
      entry.target.classList.toggle("is-visible", entry.isIntersecting);
    }), { threshold: 0.14 });
    sections.forEach(section => observer.observe(section));
    return () => observer.disconnect();
  }, []);
  return <div className="site-shell" dir="rtl">
    <header className="site-header"><Link href="/" className="brand-mark"><span className="brand-symbol">↗</span><span><strong>MADA</strong><small>ACADEMY</small></span></Link><nav className={menuOpen ? "nav-open" : ""}><a href="#method" onClick={() => setMenuOpen(false)}>كيف نعمل</a><a href="#audience" onClick={() => setMenuOpen(false)}>لمن صُممت</a><a href="#demo" onClick={() => setMenuOpen(false)}>اطلب Demo</a><a href={DASHBOARD_URL} className="mobile-nav-link" onClick={() => setMenuOpen(false)}>دخول Admin</a></nav><div className="header-actions"><a className="text-link" href={DASHBOARD_URL}>دخول Admin <ArrowUpLeft size={15} /></a><a href="#demo" className="button button-small button-dark">ابدأ الآن <ArrowLeft size={15} /></a></div><button className="menu-button" onClick={() => setMenuOpen(!menuOpen)} aria-label="فتح القائمة">{menuOpen ? <X /> : <Menu />}</button></header>
    <main>
      <section className="hero"><div className="hero-copy"><div className="eyebrow"><span className="signal-dot" /> MADA / LEARNING THAT MOVES</div><h1>لا نضيف دورة<br />إلى القائمة.<br /><em>نبني خطوة تالية.</em></h1><p className="hero-lede">Mada Academy شريكك العملي لتحويل التعلم إلى سلوك يظهر، وأداء يُقاس، ونتيجة تستمر.</p><div className="hero-actions"><a href="#demo" className="button button-primary">شاهد كيف نعمل <ArrowLeft size={18} /></a><a href="#method" className="quiet-link">اكتشف المنهج <ArrowDown size={17} /></a></div><div className="proof-strip"><div><strong>01</strong><span>فهم السياق</span></div><div><strong>02</strong><span>ممارسة موجهة</span></div><div><strong>03</strong><span>إثبات الأثر</span></div></div></div><div className="hero-visual"><div className="visual-index">/ 01 — FROM SIGNAL TO PROOF</div><div className="orbit orbit-one" /><div className="orbit orbit-two" /><div className="hero-panel"><span className="panel-label">نتيجة قابلة للرؤية</span><strong>التعلّم<br /><em>يتحرّك.</em></strong><div className="panel-foot"><span>قادة الصف الأول</span><span className="mini-arrow">↗</span></div></div><div className="floating-note"><BarChart3 size={18} /><span><b>+ أثر</b><small>يبدأ من التطبيق</small></span></div><div className="visual-number">01</div></div></section>
      <section className="ticker" aria-label="مبادئ Mada Academy"><span>LEARNING THAT MOVES</span><i>✳</i><span>مهارة تُمارس</span><i>✳</i><span>أثر يُرى</span><i>✳</i><span>مسار يستمر</span></section>
      <section className="method-section reveal-on-scroll" id="method"><div className="section-intro"><div className="eyebrow">02 / الطريقة</div><h2>من فجوة واضحة<br />إلى <em>أداء جديد.</em></h2><p>نبدأ من الواقع، لا من قالب جاهز. نربط احتياج فريقك بسلوك يمكن ملاحظته وقياسه داخل العمل.</p></div><div className="method-steps"><article><span>01</span><div><h3>نقرأ الإشارة</h3><p>نفهم أين يتعطل الأداء وما الذي يحتاجه الفريق فعلًا.</p></div><ArrowUpLeft size={20} /></article><article className="active-step"><span>02</span><div><h3>نصمم الممارسة</h3><p>نحوّل المفهوم إلى تجارب وتمارين تدخل في يوم العمل.</p></div><ArrowUpLeft size={20} /></article><article><span>03</span><div><h3>نثبت التقدم</h3><p>نرصد التغير ونصنع لغة مشتركة للخطوة التالية.</p></div><ArrowUpLeft size={20} /></article></div></section>
      <section className="audience-section reveal-on-scroll" id="audience"><div className="section-intro split-intro"><div><div className="eyebrow">03 / لمن صُممت</div><h2>لغة واحدة.<br /><em>أهداف مختلفة.</em></h2></div><p>لأن نتيجة التعلم لا تعني الشيء نفسه للجميع، نصمم الرسالة حول الشخص والقرار والسياق.</p></div><div className="audience-list">{audiences.map(({ icon: Icon, label, title, text }, index) => <article key={label} className={index === 1 ? "audience-card featured" : "audience-card"}><div className="card-top"><span className="card-icon"><Icon size={19} /></span><span>{label}</span><ArrowUpLeft size={19} /></div><h3>{title}</h3><p>{text}</p><span className="card-index">0{index + 1}</span></article>)}</div></section>
      <section className="quote-section reveal-on-scroll"><div className="quote-mark">“</div><blockquote>الفرق ليس في كمية ما نعرفه،<br /><em>بل في ما نفعله بعد ذلك.</em></blockquote><div className="quote-aside"><span className="eyebrow">MADA POINT OF VIEW</span><p>كل مسار جيد يترك وراءه سلوكًا جديدًا يمكن للفريق أن يراه ويكرره.</p></div></section>
      <section className="conversion-section reveal-on-scroll" id="demo"><div className="conversion-heading"><div><div className="eyebrow">04 / الخطوة التالية</div><h2>لنجعل التعلم<br /><em>يتقدّم.</em></h2></div><p>اختر المسار الأقرب لك. سنعود إليك بخطوة واضحة، لا بعرض عام آخر.</p></div><div className="forms-grid"><DemoForm /><RegistrationForm /></div></section>
    </main>
    <footer className="site-footer"><Link href="/" className="brand-mark"><span className="brand-symbol">↗</span><span><strong>MADA</strong><small>ACADEMY</small></span></Link><span>التعلم الذي يتحرك — 2026</span><a href="#demo">ابدأ محادثة <ArrowUpLeft size={15} /></a></footer>
  </div>;
}
